/**
 * Solidion Example: Aquarium (Phase B — sprites + Preload)
 *
 * Interactive aquarium exercising Solidion features:
 *  - L0: JSX, <Show>, <GameLoop>, <Game> input
 *  - L1a: useStateMachine (fish AI, jellyfish startle)
 *  - L1b: useSpring (fish movement), useOscillation (seaweed, jellyfish)
 *  - L2: <Preload> with fallback loading screen
 *  - Pre-allocated component pools with .map()
 *  - Pixel art sprite textures (generated by scripts/generate-assets.ts)
 */

import { createSignal, createRoot, batch } from "solid-js";
import { Game } from "solidion/components/Game";
import { GameLoop } from "solidion/components/GameLoop";
import { Show } from "solidion/components/Show";
import { Preload } from "solidion/components/Preload";
import { useStateMachine } from "solidion/hooks/useStateMachine";
import { useSpring } from "solidion/hooks/useSpring";
import { useOscillation } from "solidion/hooks/useOscillation";
import { useTween } from "solidion/hooks/useTween";
import { useSequence } from "solidion/hooks/useSequence";
import Phaser from "phaser";

const ASSETS = [
  "/assets/fish-red.png",
  "/assets/fish-teal.png",
  "/assets/fish-yellow.png",
  "/assets/jellyfish.png",
  "/assets/seaweed.png",
  "/assets/bubble.png",
  "/assets/food.png",
  "/assets/background.png",
];

const FISH_TEXTURES = ["/assets/fish-red.png", "/assets/fish-teal.png", "/assets/fish-yellow.png"];

// ── Constants ──
const W = 640, H = 480;
const SURFACE_Y = 30, FLOOR_Y = H - 30;
const TANK_L = 20, TANK_R = W - 20;
const MAX_FISH = 10, MAX_FOOD = 20, MAX_BUBBLES = 30;
const FOOD_NEAR = 150, FOOD_EAT = 20;
const FISH_COLORS = [0xff6b6b, 0x4ecdc4, 0xffe66d, 0xc084fc, 0xfb923c];

// ── Shared mutable state (components write, GameLoop reads) ──
type SlotCtrl = { activate: (...args: any[]) => void; deactivate: () => void };

interface FishMut {
  active: boolean; x: number; y: number; state: string;
  hunger: number; id: number;
  send: (e: string) => void; tick: (d: number) => void;
  setTarget: (x: number, y: number) => void;
  ctrl: SlotCtrl;
}

interface FoodMut {
  active: boolean; x: number; y: number;
  deactivate: () => void; update: () => void;
  ctrl: SlotCtrl;
}

interface BubbleMut {
  active: boolean; update: (d: number) => void;
  ctrl: SlotCtrl;
}

const fish: FishMut[] = Array.from({ length: MAX_FISH }, () => ({
  active: false, x: 0, y: 0, state: "idle", hunger: 0, id: 0,
  send: () => {}, tick: () => {}, setTarget: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

const food: FoodMut[] = Array.from({ length: MAX_FOOD }, () => ({
  active: false, x: 0, y: 0, deactivate: () => {}, update: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

const bubbles: BubbleMut[] = Array.from({ length: MAX_BUBBLES }, () => ({
  active: false, update: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

let nextFishId = 1;

// Jellyfish tick functions (set by Jellyfish components)
const jellyTicks: ((d: number) => void)[] = [];

// ============================================================
// Fish Component
// ============================================================

function Fish(props: { slot: number; onSelect: (s: number) => void }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);
  const [color, setColor] = createSignal(FISH_COLORS[0]);
  const [tex, setTex] = createSignal(FISH_TEXTURES[0]);
  const [dir, setDir] = createSignal(1);
  const [sleeping, setSleeping] = createSignal(false);
  const [sz, setSz] = createSignal(1);

  const ix = TANK_L + 60 + Math.random() * (TANK_R - TANK_L - 120);
  const iy = SURFACE_Y + 80 + Math.random() * (FLOOR_Y - SURFACE_Y - 160);
  const [target, setTarget] = createSignal({ x: ix, y: iy });

  const spring = useSpring({ target, stiffness: 15, damping: 8, initial: { x: ix, y: iy } });
  const osc = useOscillation({ amplitude: { y: 3 }, frequency: 0.5, phase: i * 1.7 });

  // Pop-in animation when fish is activated
  const popIn = useTween({
    from: { scale: 0 },
    to: { scale: 1 },
    duration: 400,
    ease: "Back.easeOut",
    playing: () => active(),
  });

  // Feeding sequence: approach → eat → satisfied
  const [eating, setEating] = createSignal(false);
  const feedSeq = useSequence([
    { action: "approach", duration: 800, onStart: () => setEating(true) },
    { action: "munch", duration: 400 },
    { action: "satisfied", duration: 600, onStart: () => setEating(false) },
  ]);

  const machine = useStateMachine<"idle" | "swim" | "eat" | "sleep">({
    initial: "idle",
    states: {
      idle: {
        duration: 2000 + Math.random() * 2000, onComplete: "swim",
        on: { FOOD_NEARBY: "eat" },
        onEnter: () => setTarget({ x: spring().x, y: spring().y }),
      },
      swim: {
        duration: 3000 + Math.random() * 3000, onComplete: "idle",
        on: { FOOD_NEARBY: "eat", SLEEPY: "sleep" },
        onEnter: () => {
          const tx = TANK_L + 40 + Math.random() * (TANK_R - TANK_L - 80);
          const ty = SURFACE_Y + 60 + Math.random() * (FLOOR_Y - SURFACE_Y - 120);
          setTarget({ x: tx, y: ty });
          setDir(tx > spring().x ? 1 : -1);
        },
      },
      eat: { duration: 2500, onComplete: "idle", onEnter: () => feedSeq.play() },
      sleep: {
        duration: 5000 + Math.random() * 3000, onComplete: "idle",
        on: { WAKE: "idle" },
        onEnter: () => { setSleeping(true); setTarget({ x: spring().x, y: FLOOR_Y - 50 }); },
        onExit: () => setSleeping(false),
      },
    },
  });

  // Register callbacks for GameLoop
  fish[i].tick = (d) => machine.tick(d);
  fish[i].send = (e) => machine.send(e);
  fish[i].setTarget = (x, y) => { setTarget({ x, y }); setDir(x > spring().x ? 1 : -1); };
  fish[i].ctrl = {
    activate: (c: number, s: number, t: string) => {
      const id = nextFishId++;
      batch(() => { setColor(c); setTex(t); setSz(s); setActive(true); setSleeping(false); });
      const sx = TANK_L + 60 + Math.random() * (TANK_R - TANK_L - 120);
      const sy = SURFACE_Y + 80 + Math.random() * (FLOOR_Y - SURFACE_Y - 160);
      setTarget({ x: sx, y: sy });
      fish[i].active = true; fish[i].id = id; fish[i].hunger = 0;
    },
    deactivate: () => { setActive(false); fish[i].active = false; },
  };

  const fx = () => {
    const x = Phaser.Math.Clamp(spring().x, TANK_L + 20, TANK_R - 20);
    fish[i].x = x; fish[i].state = machine.state();
    return x;
  };
  const fy = () => {
    const o = machine.is("idle") || machine.is("sleep") ? osc().y : 0;
    const y = Phaser.Math.Clamp(spring().y + o, SURFACE_Y + 30, FLOOR_Y - 20);
    fish[i].y = y;
    return y;
  };
  const s = () => sz() * popIn().scale;

  return (
    <Show when={active()}>
      <rectangle x={fx()} y={fy()} width={40 * s()} height={28 * s()}
        fillColor={0x000000} origin={0.5} depth={13} alpha={0.001}
        onClick={() => props.onSelect(i)} />
      <sprite x={fx()} y={fy()} texture={tex()}
        origin={0.5} depth={10}
        scaleX={dir() * s() * 2} scaleY={s() * 2}
        alpha={sleeping() ? 0.5 : 1} />
      <rectangle x={fx() - dir() * 18 * s()} y={fy()}
        width={10 * s()} height={12 * s()}
        fillColor={color()} origin={0.5} depth={9} alpha={sleeping() ? 0.4 : 0.8} />
      <ellipse x={fx() + dir() * 8 * s()} y={fy() - 2 * s()}
        width={5 * s()}
        height={(sleeping() || feedSeq.current() === "munch") ? 1 * s() : 5 * s()}
        fillColor={0xffffff} origin={0.5} depth={11} />
      <ellipse x={fx() + dir() * 9 * s()} y={fy() - 2 * s()}
        width={2.5 * s()}
        height={(sleeping() || feedSeq.current() === "munch") ? 0.5 * s() : 2.5 * s()}
        fillColor={0x111111} origin={0.5} depth={12} />
    </Show>
  );
}

// ============================================================
// Jellyfish Component
// ============================================================

function Jellyfish(props: { baseX: number; baseY: number }) {
  const [startled, setStartled] = createSignal(false);

  const drift = useOscillation({
    amplitude: { y: 40, x: 8 }, frequency: 0.2, phase: props.baseX * 0.01,
  });

  const machine = useStateMachine<"drift" | "startled">({
    initial: "drift",
    states: {
      drift: { on: { STARTLE: "startled" } },
      startled: {
        duration: 800, onComplete: "drift",
        onEnter: () => setStartled(true), onExit: () => setStartled(false),
      },
    },
  });

  const startle = () => machine.send("STARTLE");
  jellyTicks.push((d) => machine.tick(d));

  const jx = () => props.baseX + (startled() ? 0 : drift().x);
  const jy = () => props.baseY + (startled() ? -10 : drift().y);

  return (
    <>
      <ellipse x={jx()} y={jy()} width={30} height={24}
        fillColor={0xcc88ff} origin={0.5} depth={8}
        alpha={startled() ? 0.4 : 0.6} onClick={startle} />
      <rectangle x={jx() - 6} y={jy() + 18} width={2} height={16}
        fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4} />
      <rectangle x={jx()} y={jy() + 20} width={2} height={20}
        fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4} />
      <rectangle x={jx() + 6} y={jy() + 18} width={2} height={16}
        fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4} />
    </>
  );
}

// ============================================================
// Seaweed Component
// ============================================================

function Seaweed(props: { x: number; height: number; index: number }) {
  const sway = useOscillation({
    amplitude: { x: 8 }, frequency: 0.3 + props.index * 0.08, phase: props.index * 1.2,
  });
  const h = props.height;
  const sx = () => props.x + sway().x;

  return (
    <>
      <rectangle x={sx()} y={FLOOR_Y - h / 2} width={6} height={h}
        fillColor={0x2d8b46} origin={0.5} depth={2} alpha={0.7} />
      <rectangle x={sx() + 8} y={FLOOR_Y - h * 0.3} width={5} height={h * 0.6}
        fillColor={0x3aad5c} origin={0.5} depth={2} alpha={0.5} />
    </>
  );
}

// ============================================================
// Bubble Component (useOscillation for wobble, manual velocity)
// ============================================================

function Bubble(props: { slot: number }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);
  const [px, setPx] = createSignal(0);
  const [py, setPy] = createSignal(FLOOR_Y);
  const [dia, setDia] = createSignal(4);

  const wobble = useOscillation({
    amplitude: { x: 3 }, frequency: 1.5 + Math.random() * 0.5, phase: i * 2.1,
  });

  let _bx = 0, _y = FLOOR_Y, _spd = 0.7, _on = false;

  bubbles[i].ctrl = {
    activate: (x: number) => {
      _bx = x; _y = FLOOR_Y - 10; _spd = 0.5 + Math.random() * 1.0; _on = true;
      bubbles[i].active = true;
      batch(() => { setPx(x); setPy(_y); setDia(3 + Math.random() * 4); setActive(true); });
    },
    deactivate: () => { _on = false; bubbles[i].active = false; setActive(false); },
  };

  bubbles[i].update = () => {
    if (!_on) return;
    _y -= _spd;
    if (_y < SURFACE_Y) { bubbles[i].ctrl.deactivate(); }
    else { setPx(_bx + wobble().x); setPy(_y); }
  };

  return (
    <ellipse x={px()} y={py()} width={dia()} height={dia()}
      fillColor={0x88ccee} origin={0.5} depth={4} alpha={0.6} visible={active()} />
  );
}

// ============================================================
// Food Component (useVelocity for sinking)
// ============================================================

function Food(props: { slot: number }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);
  const [px, setPx] = createSignal(0);
  const [py, setPy] = createSignal(0);

  let _x = 0, _y = 0, _on = false;

  const deactivate = () => { _on = false; food[i].active = false; setActive(false); };

  food[i].deactivate = deactivate;
  food[i].ctrl = {
    activate: (x: number, y: number) => {
      _x = x; _y = y; _on = true;
      Object.assign(food[i], { active: true, x, y });
      batch(() => { setPx(x); setPy(y); setActive(true); });
    },
    deactivate,
  };

  food[i].update = () => {
    if (!_on) return;
    _y += 0.3;
    if (_y > FLOOR_Y) { deactivate(); }
    else { food[i].x = _x; food[i].y = _y; setPy(_y); }
  };

  return (
    <ellipse x={px()} y={py()} width={6} height={6}
      fillColor={0xddaa44} origin={0.5} depth={3} visible={active()} />
  );
}

// ============================================================
// App
// ============================================================

function App() {
  const [phase, setPhase] = createSignal<"title" | "aquarium">("title");
  const [fishCount, setFishCount] = createSignal(0);
  const [selIdx, setSelIdx] = createSignal(-1);
  const [showPanel, setShowPanel] = createSignal(false);
  let bubbleTimer = 0, initialized = false;

  function spawnFish() {
    const s = fish.findIndex(f => !f.active);
    if (s < 0) return;
    const ti = Math.floor(Math.random() * FISH_TEXTURES.length);
    const col = FISH_COLORS[ti];
    const tex = FISH_TEXTURES[ti];
    fish[s].ctrl.activate(col, 0.8 + Math.random() * 0.4, tex);
    setFishCount(c => c + 1);
  }

  const handlePointerDown = (ptr: Phaser.Input.Pointer) => {
    if (phase() === "title") {
      setPhase("aquarium");
      if (!initialized) { initialized = true; spawnFish(); spawnFish(); spawnFish(); }
      return;
    }
    if (ptr.x > W - 120 && ptr.y < 35) return;
    if (selIdx() >= 0 && ptr.x > W - 160 && ptr.y > H / 2 - 100 && ptr.y < H / 2 + 100) return;
    if (ptr.y < SURFACE_Y + 10 || ptr.y > FLOOR_Y) return;
    if (ptr.x < TANK_L || ptr.x > TANK_R) return;

    const s = food.findIndex(f => !f.active);
    if (s >= 0) food[s].ctrl.activate(ptr.x, ptr.y);
  };

  const releaseFish = () => {
    const idx = selIdx();
    if (idx < 0) return;
    fish[idx].ctrl.deactivate();
    setSelIdx(-1); setShowPanel(false); setFishCount(c => c - 1);
  };

  const selectFish = (s: number) => { setSelIdx(s); setShowPanel(true); };

  // ── Master GameLoop ──
  const handleUpdate = (_t: number, delta: number) => {
    if (phase() !== "aquarium") return;

    // Fish AI: tick machines, check food proximity
    for (let i = 0; i < MAX_FISH; i++) {
      const f = fish[i];
      if (!f.active) continue;
      f.tick(delta);
      f.hunger += delta * 0.01;

      // Nearest food
      let ni = -1, nd = Infinity;
      for (let j = 0; j < MAX_FOOD; j++) {
        if (!food[j].active) continue;
        const dx = food[j].x - f.x, dy = food[j].y - f.y;
        const d = Math.sqrt(dx * dx + dy * dy);
        if (d < nd) { nd = d; ni = j; }
      }

      if (f.state === "eat" && ni >= 0 && nd < FOOD_EAT) {
        food[ni].deactivate(); f.hunger = 0;
      } else if ((f.state === "idle" || f.state === "swim") && ni >= 0 && nd < FOOD_NEAR && f.hunger > 30) {
        f.setTarget(food[ni].x, food[ni].y);
        f.send("FOOD_NEARBY");
      }

      if (f.hunger > 100 && f.state === "swim" && Math.random() < 0.001) f.send("SLEEPY");
    }

    // Jellyfish
    for (const jt of jellyTicks) jt(delta);

    // Food sinking
    for (let j = 0; j < MAX_FOOD; j++) food[j].update();

    // Bubble movement + spawning
    for (let j = 0; j < MAX_BUBBLES; j++) bubbles[j].update(delta);
    bubbleTimer -= delta;
    if (bubbleTimer <= 0) {
      bubbleTimer = 200 + Math.random() * 500;
      const s = bubbles.findIndex(b => !b.active);
      if (s >= 0) bubbles[s].ctrl.activate(TANK_L + 20 + Math.random() * (TANK_R - TANK_L - 40));
    }
  };

  const sel = () => selIdx() >= 0 ? fish[selIdx()] : null;

  return (
    <Game width={W} height={H} backgroundColor={0x0a1a2e} parent="game-container"
      onPointerDown={handlePointerDown}>
      <GameLoop onUpdate={handleUpdate} />

      {/* Title Screen */}
      <Show when={phase() === "title"}>
        <rectangle x={W / 2} y={H / 2} width={W} height={H}
          fillColor={0x0a1a2e} origin={0.5} depth={100} />
        <text x={W / 2} y={H / 2 - 40} text="Solidion Aquarium"
          fontSize={36} fontFamily="Georgia, serif" color="#4488cc" origin={0.5} depth={101} />
        <text x={W / 2} y={H / 2 + 20} text="tap to start"
          fontSize={16} fontFamily="monospace" color="#336688" origin={0.5} depth={101} />
        <ellipse x={W / 2} y={H / 2 + 80} width={32} height={18}
          fillColor={0x4ecdc4} origin={0.5} depth={101} alpha={0.6} />
        <rectangle x={W / 2 - 18} y={H / 2 + 80} width={10} height={12}
          fillColor={0x4ecdc4} origin={0.5} depth={101} alpha={0.5} />
      </Show>

      {/* Preload assets with loading screen */}
      <Preload
        assets={ASSETS}
        fallback={
          <>
            <rectangle x={W / 2} y={H / 2} width={W} height={H}
              fillColor={0x0a1a2e} origin={0.5} depth={50} />
            <text x={W / 2} y={H / 2 - 10} text="Loading aquarium..."
              fontSize={16} fontFamily="monospace" color="#336688" origin={0.5} depth={51} />
            <ellipse x={W / 2} y={H / 2 + 30} width={20} height={12}
              fillColor={0x4ecdc4} origin={0.5} depth={51} alpha={0.5} />
          </>
        }
      >

      {/* Tank */}
      <rectangle x={W / 2} y={SURFACE_Y + (FLOOR_Y - SURFACE_Y) / 2}
        width={W - 40} height={FLOOR_Y - SURFACE_Y}
        fillColor={0x0e2040} origin={0.5} depth={0} alpha={0.5} />
      <rectangle x={W / 2} y={FLOOR_Y + 15} width={W - 40} height={30}
        fillColor={0x8b7355} origin={0.5} depth={1} />
      <rectangle x={W / 2} y={SURFACE_Y} width={W - 40} height={2}
        fillColor={0x4488aa} origin={0.5} depth={5} alpha={0.5} />

      {/* Seaweed (5) */}
      {[{ x: 80, h: 40 }, { x: 200, h: 55 }, { x: 350, h: 70 }, { x: 500, h: 85 }, { x: 580, h: 60 }]
        .map((sw, i) => <Seaweed x={sw.x} height={sw.h} index={i} />)}

      {/* Jellyfish (2) */}
      <Jellyfish baseX={520} baseY={150} />
      <Jellyfish baseX={120} baseY={200} />

      {/* Bubbles pool */}
      {Array.from({ length: MAX_BUBBLES }, (_, i) => <Bubble slot={i} />)}

      {/* Food pool */}
      {Array.from({ length: MAX_FOOD }, (_, i) => <Food slot={i} />)}

      {/* Fish pool */}
      {Array.from({ length: MAX_FISH }, (_, i) => <Fish slot={i} onSelect={selectFish} />)}

      {/* HUD */}
      <Show when={phase() === "aquarium"}>
        <rectangle x={W - 60} y={16} width={100} height={24}
          fillColor={0x225588} origin={0.5} depth={20} onClick={() => spawnFish()} />
        <text x={W - 60} y={16} text="+ Add Fish"
          fontSize={11} fontFamily="monospace" color="#aaccee" origin={0.5} depth={21} />
        <text x={20} y={16} text={`Fish: ${fishCount()}`}
          fontSize={12} fontFamily="monospace" color="#668899" originX={0} originY={0.5} depth={20} />
      </Show>

      {/* Stats Panel */}
      <Show when={showPanel() && selIdx() >= 0}>
        <rectangle x={W - 80} y={H / 2} width={140} height={180}
          fillColor={0x112233} origin={0.5} depth={30} alpha={0.9} />
        <text x={W - 80} y={H / 2 - 60} text={`Fish #${sel()?.id ?? ""}`}
          fontSize={14} fontFamily="monospace" color="#88bbdd" origin={0.5} depth={31} />
        <text x={W - 80} y={H / 2 - 30} text={`State: ${sel()?.state ?? ""}`}
          fontSize={11} fontFamily="monospace" color="#668899" origin={0.5} depth={31} />
        <text x={W - 80} y={H / 2 - 10} text={`Hunger: ${Math.floor(sel()?.hunger ?? 0)}`}
          fontSize={11} fontFamily="monospace" color="#668899" origin={0.5} depth={31} />
        <rectangle x={W - 80} y={H / 2 + 30} width={80} height={24}
          fillColor={0x884444} origin={0.5} depth={31} onClick={releaseFish} />
        <text x={W - 80} y={H / 2 + 30} text="Release"
          fontSize={11} fontFamily="monospace" color="#ffaaaa" origin={0.5} depth={32} />
        <rectangle x={W - 80} y={H / 2 + 60} width={80} height={24}
          fillColor={0x444466} origin={0.5} depth={31}
          onClick={() => { setSelIdx(-1); setShowPanel(false); }} />
        <text x={W - 80} y={H / 2 + 60} text="Close"
          fontSize={11} fontFamily="monospace" color="#aaaacc" origin={0.5} depth={32} />
      </Show>

      </Preload>
    </Game>
  );
}

// ── Mount ──
createRoot(() => {
  const el = App();
  if (el instanceof HTMLElement) document.getElementById("game-container")?.appendChild(el);
});
