/**
 * Solidion Example: Aquarium (Phase B — sprites + Preload)
 *
 * Interactive aquarium exercising Solidion features:
 *  - L0: JSX, <Show>, <GameLoop>, <Game> input
 *  - L1a: useStateMachine (fish AI, jellyfish startle)
 *  - L1b: useSpring (fish movement), useOscillation (seaweed, jellyfish)
 *  - L2: <Preload> with fallback loading screen
 *  - Pre-allocated component pools with .map()
 *  - Pixel art sprite textures (generated by scripts/generate-assets.ts)
 */

import { createSignal, createRoot, batch } from "solid-js";
import { Game } from "solidion/components/Game";
import { GameLoop } from "solidion/components/GameLoop";
import { Show } from "solidion/components/Show";
import { Scene } from "solidion/components/Scene";
import { Preload } from "solidion/components/Preload";
import { useStateMachine } from "solidion/hooks/useStateMachine";
import { useSpring } from "solidion/hooks/useSpring";
import { useOscillation } from "solidion/hooks/useOscillation";
import { useTween } from "solidion/hooks/useTween";
import { useSequence } from "solidion/hooks/useSequence";
import { useFollow } from "solidion/hooks/useFollow";
import { useVelocity } from "solidion/hooks/useVelocity";
import { OscillateBehavior, SpringBehavior } from "solidion/behaviors";
import * as debug from "solidion/debug";
import Phaser from "phaser";

debug.enable();

const ASSETS = [
  "/assets/fish-red.png",
  "/assets/fish-teal.png",
  "/assets/fish-yellow.png",
  "/assets/jellyfish.png",
  "/assets/seaweed.png",
  "/assets/bubble.png",
  "/assets/food.png",
  "/assets/background.png",
];

const FISH_TEXTURES = ["/assets/fish-red.png", "/assets/fish-teal.png", "/assets/fish-yellow.png"];

// ── Constants ──
const W = 640, H = 480;
const SURFACE_Y = 30, FLOOR_Y = H - 30;
const TANK_L = 20, TANK_R = W - 20;
const MAX_FISH = 10, MAX_FOOD = 20, MAX_BUBBLES = 30;
const FOOD_NEAR = 150, FOOD_EAT = 20;
const FISH_COLORS = [0xff6b6b, 0x4ecdc4, 0xffe66d, 0xc084fc, 0xfb923c];

// ── Shared mutable state (components write, GameLoop reads) ──
type SlotCtrl = { activate: (...args: any[]) => void; deactivate: () => void };

interface FishMut {
  active: boolean; x: number; y: number; state: string;
  hunger: number; id: number;
  send: (e: string) => void; tick: (d: number) => void;
  setTarget: (x: number, y: number) => void;
  ctrl: SlotCtrl;
}

interface FoodMut {
  active: boolean; x: number; y: number;
  deactivate: () => void; update: () => void;
  ctrl: SlotCtrl;
}

interface BubbleMut {
  active: boolean; update: (d: number) => void;
  ctrl: SlotCtrl;
}

const fish: FishMut[] = Array.from({ length: MAX_FISH }, () => ({
  active: false, x: 0, y: 0, state: "idle", hunger: 0, id: 0,
  send: () => {}, tick: () => {}, setTarget: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

const food: FoodMut[] = Array.from({ length: MAX_FOOD }, () => ({
  active: false, x: 0, y: 0, deactivate: () => {}, update: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

const bubbles: BubbleMut[] = Array.from({ length: MAX_BUBBLES }, () => ({
  active: false, update: () => {},
  ctrl: { activate: () => {}, deactivate: () => {} },
}));

let nextFishId = 1;

// Jellyfish tick functions (set by Jellyfish components)
const jellyTicks: ((d: number) => void)[] = [];

// ============================================================
// Fish Component
// ============================================================

function Fish(props: { slot: number; onSelect: (s: number) => void }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);
  const [color, setColor] = createSignal(FISH_COLORS[0]);
  const [tex, setTex] = createSignal(FISH_TEXTURES[0]);
  const [dir, setDir] = createSignal(1);
  const [sleeping, setSleeping] = createSignal(false);
  const [sz, setSz] = createSignal(1);

  const ix = TANK_L + 60 + Math.random() * (TANK_R - TANK_L - 120);
  const iy = SURFACE_Y + 80 + Math.random() * (FLOOR_Y - SURFACE_Y - 160);
  const [target, setTarget] = createSignal({ x: ix, y: iy });

  const spring = useSpring({ target, stiffness: 15, damping: 8, initial: { x: ix, y: iy } });
  const osc = useOscillation({ amplitude: { y: 3 }, frequency: 0.5, phase: i * 1.7 });

  // Pop-in animation when fish is activated
  const popIn = useTween({
    from: { scale: 0 },
    to: { scale: 1 },
    duration: 400,
    ease: "Back.easeOut",
    playing: () => active(),
  });

  // Feeding sequence: approach → eat → satisfied
  const [eating, setEating] = createSignal(false);
  const feedSeq = useSequence([
    { action: "approach", duration: 800, onStart: () => setEating(true) },
    { action: "munch", duration: 400 },
    { action: "satisfied", duration: 600, onStart: () => setEating(false) },
  ]);

  const machine = useStateMachine<"idle" | "swim" | "eat" | "sleep">({
    initial: "idle",
    states: {
      idle: {
        duration: 2000 + Math.random() * 2000, onComplete: "swim",
        on: { FOOD_NEARBY: "eat" },
        onEnter: () => setTarget({ x: spring().x, y: spring().y }),
      },
      swim: {
        duration: 3000 + Math.random() * 3000, onComplete: "idle",
        on: { FOOD_NEARBY: "eat", SLEEPY: "sleep" },
        onEnter: () => {
          const tx = TANK_L + 40 + Math.random() * (TANK_R - TANK_L - 80);
          const ty = SURFACE_Y + 60 + Math.random() * (FLOOR_Y - SURFACE_Y - 120);
          setTarget({ x: tx, y: ty });
          setDir(tx > spring().x ? 1 : -1);
        },
      },
      eat: { duration: 2500, onComplete: "idle", onEnter: () => feedSeq.play() },
      sleep: {
        duration: 5000 + Math.random() * 3000, onComplete: "idle",
        on: { WAKE: "idle" },
        onEnter: () => { setSleeping(true); setTarget({ x: spring().x, y: FLOOR_Y - 50 }); },
        onExit: () => setSleeping(false),
      },
    },
  });

  // Register callbacks for GameLoop
  fish[i].tick = (d) => machine.tick(d);
  fish[i].send = (e) => machine.send(e);
  fish[i].setTarget = (x, y) => { setTarget({ x, y }); setDir(x > spring().x ? 1 : -1); };
  fish[i].ctrl = {
    activate: (c: number, s: number, t: string) => {
      const id = nextFishId++;
      batch(() => { setColor(c); setTex(t); setSz(s); setActive(true); setSleeping(false); });
      const sx = TANK_L + 60 + Math.random() * (TANK_R - TANK_L - 120);
      const sy = SURFACE_Y + 80 + Math.random() * (FLOOR_Y - SURFACE_Y - 160);
      setTarget({ x: sx, y: sy });
      fish[i].active = true; fish[i].id = id; fish[i].hunger = 0;
    },
    deactivate: () => { setActive(false); fish[i].active = false; },
  };

  const fx = () => {
    const x = Phaser.Math.Clamp(spring().x, TANK_L + 20, TANK_R - 20);
    fish[i].x = x; fish[i].state = machine.state();
    return x;
  };
  const fy = () => {
    const o = machine.is("idle") || machine.is("sleep") ? osc().y : 0;
    const y = Phaser.Math.Clamp(spring().y + o, SURFACE_Y + 30, FLOOR_Y - 20);
    fish[i].y = y;
    return y;
  };
  const s = () => sz() * popIn().scale;

  return (
    <Show when={active()}>
      {/* Hit area uses sz() not s() — always full size, not affected by pop-in */}
      <rectangle x={fx()} y={fy()} width={40 * sz()} height={28 * sz()}
        fillColor={0x000000} origin={0.5} depth={13} alpha={0.001}
        onClick={() => props.onSelect(i)} />
      <sprite x={fx()} y={fy()} texture={tex()}
        origin={0.5} depth={10}
        scaleX={dir() * s() * 2} scaleY={s() * 2}
        alpha={sleeping() ? 0.5 : 1}
        ref={(el: any) => { (fish[i] as any)._ref = el; }} />
<ellipse x={fx() + dir() * 8 * s()} y={fy() - 2 * s()}
        width={5 * s()}
        height={(sleeping() || feedSeq.current() === "munch") ? 1 * s() : 5 * s()}
        fillColor={0xffffff} origin={0.5} depth={11} />
      <ellipse x={fx() + dir() * 9 * s()} y={fy() - 2 * s()}
        width={2.5 * s()}
        height={(sleeping() || feedSeq.current() === "munch") ? 0.5 * s() : 2.5 * s()}
        fillColor={0x111111} origin={0.5} depth={12} />
    </Show>
  );
}

// ============================================================
// Fry Component (baby fish following parent)
// ============================================================

const MAX_FRY = 5;
const fryParents: number[] = Array(MAX_FRY).fill(-1); // parent fish slot index
const fryActive: [() => boolean, (v: boolean) => void][] = [];

function Fry(props: { slot: number }) {
  const j = props.slot;
  const [active, setActive] = createSignal(false);
  const [color, setColor] = createSignal(FISH_COLORS[0]);
  fryActive[j] = [active, setActive];

  const parentPos = (): { x: number; y: number } => {
    const pi = fryParents[j];
    if (pi < 0 || !fish[pi].active) return { x: W / 2, y: H / 2 };
    return { x: fish[pi].x, y: fish[pi].y };
  };

  // Follow parent with lag + small offset
  const offset = { x: (j % 2 === 0 ? -1 : 1) * (12 + j * 4), y: 8 + j * 3 };
  const followTarget = () => ({ x: parentPos().x + offset.x, y: parentPos().y + offset.y });
  const pos = useFollow({ target: followTarget, speed: 0.08 + j * 0.02 });

  return (
    <Show when={active()}>
      <ellipse x={pos().x} y={pos().y} width={12} height={7}
        fillColor={color()} origin={0.5} depth={10} alpha={0.7} />
      <ellipse x={pos().x + 3} y={pos().y - 1} width={2} height={2}
        fillColor={0xffffff} origin={0.5} depth={11} />
    </Show>
  );
}

// ============================================================
// Jellyfish Component
// ============================================================

function Jellyfish(props: { baseX: number; baseY: number }) {
  const [startled, setStartled] = createSignal(false);

  // Slow drift (12s cycle for natural movement)
  const drift = useOscillation({
    amplitude: { y: 30, x: 6 }, frequency: 0.08, phase: props.baseX * 0.01,
  });

  // Pulsing size (3 pulses per drift cycle ≈ 0.24 Hz)
  const pulse = useOscillation({
    amplitude: { x: 4, y: 3 }, frequency: 0.24, phase: props.baseX * 0.03,
  });

  const machine = useStateMachine<"drift" | "startled">({
    initial: "drift",
    states: {
      drift: { on: { STARTLE: "startled" } },
      startled: {
        duration: 800, onComplete: "drift",
        onEnter: () => setStartled(true), onExit: () => setStartled(false),
      },
    },
  });

  const startle = () => machine.send("STARTLE");
  jellyTicks.push((d) => machine.tick(d));

  const jx = () => props.baseX + (startled() ? 0 : drift().x);
  const jy = () => props.baseY + (startled() ? -10 : drift().y);
  // Bell size pulses (breathing) — contracts when startled
  const bellW = () => startled() ? 24 : 30 + pulse().x;
  const bellH = () => startled() ? 18 : 24 + pulse().y;

  return (
    <>
      {/* Bell — size pulsing creates breathing animation */}
      <ellipse x={jx()} y={jy()} width={bellW()} height={bellH()}
        fillColor={0xcc88ff} origin={0.5} depth={8}
        alpha={startled() ? 0.4 : 0.6} onClick={startle} />
      {/* Tentacles — attached to bottom of bell, with L1c OscillateBehavior sway */}
      {(() => {
        let t1: any, t2: any, t3: any;
        return (
          <>
            <rectangle x={jx() - 6} y={jy() + bellH() / 2 + 2} width={2} height={16}
              fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4}
              ref={(el: any) => { t1 = el; }} />
            <rectangle x={jx()} y={jy() + bellH() / 2 + 3} width={2} height={20}
              fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4}
              ref={(el: any) => { t2 = el; }} />
            <rectangle x={jx() + 6} y={jy() + bellH() / 2 + 2} width={2} height={16}
              fillColor={0xbb77ee} origin={0.5} depth={7} alpha={0.4}
              ref={(el: any) => { t3 = el; }} />
            {/* L1c: OscillateBehavior makes each tentacle sway independently */}
            {t1 && <OscillateBehavior parent={t1} amplitude={{ x: 2 }} frequency={0.6} phase={0} />}
            {t2 && <OscillateBehavior parent={t2} amplitude={{ x: 3 }} frequency={0.5} phase={1.2} />}
            {t3 && <OscillateBehavior parent={t3} amplitude={{ x: 2 }} frequency={0.7} phase={2.4} />}
          </>
        );
      })()}
    </>
  );
}

// ============================================================
// Seaweed Component
// ============================================================

function Seaweed(props: { x: number; height: number; index: number }) {
  const sway = useOscillation({
    amplitude: { x: 8 }, frequency: 0.3 + props.index * 0.08, phase: props.index * 1.2,
  });
  const h = props.height;
  const sx = () => props.x + sway().x;

  return (
    <>
      <rectangle x={sx()} y={FLOOR_Y - h / 2} width={6} height={h}
        fillColor={0x2d8b46} origin={0.5} depth={2} alpha={0.7} />
      <rectangle x={sx() + 8} y={FLOOR_Y - h * 0.3} width={5} height={h * 0.6}
        fillColor={0x3aad5c} origin={0.5} depth={2} alpha={0.5} />
    </>
  );
}

// ============================================================
// Bubble Component (useVelocity for rising + useOscillation for wobble)
// ============================================================

function Bubble(props: { slot: number }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);
  const [dia, setDia] = createSignal(4);

  const wobble = useOscillation({
    amplitude: { x: 3 }, frequency: 1.5 + Math.random() * 0.5, phase: i * 2.1,
  });

  const vel = useVelocity({ bounds: { y: [SURFACE_Y, FLOOR_Y] } });

  bubbles[i].ctrl = {
    activate: (x: number) => {
      vel.reset({ x, y: FLOOR_Y - 10 }, { x: 0, y: -(30 + Math.random() * 60) });
      vel.setActive(true);
      bubbles[i].active = true;
      batch(() => { setDia(3 + Math.random() * 4); setActive(true); });
    },
    deactivate: () => { vel.setActive(false); bubbles[i].active = false; setActive(false); },
  };

  bubbles[i].update = () => {
    if (!bubbles[i].active) return;
    // Deactivate when reaching surface
    if (vel.pos().y <= SURFACE_Y + 1) { bubbles[i].ctrl.deactivate(); }
  };

  return (
    <ellipse x={vel.pos().x + wobble().x} y={vel.pos().y} width={dia()} height={dia()}
      fillColor={0x88ccee} origin={0.5} depth={4} alpha={0.6} visible={active()} />
  );
}

// ============================================================
// Food Component (useVelocity for sinking)
// ============================================================

function Food(props: { slot: number }) {
  const i = props.slot;
  const [active, setActive] = createSignal(false);

  const vel = useVelocity({ bounds: { y: [SURFACE_Y, FLOOR_Y] } });

  const deactivate = () => { vel.setActive(false); food[i].active = false; setActive(false); };

  food[i].deactivate = deactivate;
  food[i].ctrl = {
    activate: (x: number, y: number) => {
      vel.reset({ x, y }, { x: 0, y: 18 }); // sinking speed
      vel.setActive(true);
      Object.assign(food[i], { active: true, x, y });
      setActive(true);
    },
    deactivate,
  };

  food[i].update = () => {
    if (!food[i].active) return;
    // Update mutable position for fish AI proximity checks
    food[i].x = vel.pos().x;
    food[i].y = vel.pos().y;
    if (vel.pos().y >= FLOOR_Y - 1) { deactivate(); }
  };

  return (
    <ellipse x={vel.pos().x} y={vel.pos().y} width={6} height={6}
      fillColor={0xddaa44} origin={0.5} depth={3} visible={active()} />
  );
}

// ============================================================
// App
// ============================================================

function App() {
  const [phase, setPhase] = createSignal<"title" | "aquarium">("title");
  const [fishCount, setFishCount] = createSignal(0);
  const [selIdx, setSelIdx] = createSignal(-1);
  const [showPanel, setShowPanel] = createSignal(false);
  const [debugInfo, setDebugInfo] = createSignal("");
  let bubbleTimer = 0, initialized = false, debugTimer = 0;

  function spawnFish() {
    const s = fish.findIndex(f => !f.active);
    if (s < 0) return;
    const ti = Math.floor(Math.random() * FISH_TEXTURES.length);
    const col = FISH_COLORS[ti];
    const tex = FISH_TEXTURES[ti];
    fish[s].ctrl.activate(col, 0.8 + Math.random() * 0.4, tex);
    setFishCount(c => c + 1);

    // 50% chance to spawn a fry (baby fish) following this parent
    if (Math.random() < 0.2) {
      const fj = fryParents.findIndex((_, j) => !fryActive[j]?.[0]());
      if (fj >= 0) {
        fryParents[fj] = s;
        fryActive[fj]?.[1](true);
      }
    }
  }

  const handlePointerDown = (ptr: Phaser.Input.Pointer) => {
    if (phase() === "title") {
      setPhase("aquarium");
      if (!initialized) { initialized = true; spawnFish(); spawnFish(); spawnFish(); }
      return;
    }
    if (ptr.x > W - 120 && ptr.y < 35) return;
    if (selIdx() >= 0 && ptr.x > W - 160 && ptr.y > H / 2 - 100 && ptr.y < H / 2 + 100) return;
    if (ptr.y < SURFACE_Y + 10 || ptr.y > FLOOR_Y) return;
    if (ptr.x < TANK_L || ptr.x > TANK_R) return;

    const s = food.findIndex(f => !f.active);
    if (s >= 0) food[s].ctrl.activate(ptr.x, ptr.y);
  };

  const releaseFish = () => {
    const idx = selIdx();
    if (idx < 0) return;
    fish[idx].ctrl.deactivate();
    // Also deactivate any fry following this fish
    for (let j = 0; j < MAX_FRY; j++) {
      if (fryParents[j] === idx) {
        fryActive[j]?.[1](false);
        fryParents[j] = -1;
      }
    }
    setSelIdx(-1); setShowPanel(false); setFishCount(c => c - 1);
  };

  const selectFish = (s: number) => { setSelIdx(s); setShowPanel(true); };

  // ── Master GameLoop ──
  const handleUpdate = (_t: number, delta: number) => {
    if (phase() !== "aquarium") return;

    // Fish AI: tick machines, check food proximity
    for (let i = 0; i < MAX_FISH; i++) {
      const f = fish[i];
      if (!f.active) continue;
      f.tick(delta);
      f.hunger += delta * 0.003;

      // Nearest food
      let ni = -1, nd = Infinity;
      for (let j = 0; j < MAX_FOOD; j++) {
        if (!food[j].active) continue;
        const dx = food[j].x - f.x, dy = food[j].y - f.y;
        const d = Math.sqrt(dx * dx + dy * dy);
        if (d < nd) { nd = d; ni = j; }
      }

      if (f.state === "eat" && ni >= 0 && nd < FOOD_EAT) {
        food[ni].deactivate(); f.hunger = 0;
      } else if ((f.state === "idle" || f.state === "swim") && ni >= 0 && nd < FOOD_NEAR && f.hunger > 30) {
        f.setTarget(food[ni].x, food[ni].y);
        f.send("FOOD_NEARBY");
      }

      if (f.hunger > 100 && f.state === "swim" && Math.random() < 0.001) f.send("SLEEPY");
    }

    // Jellyfish
    for (const jt of jellyTicks) jt(delta);

    // Food sinking
    for (let j = 0; j < MAX_FOOD; j++) food[j].update();

    // Bubble movement + spawning
    for (let j = 0; j < MAX_BUBBLES; j++) bubbles[j].update(delta);
    bubbleTimer -= delta;
    if (bubbleTimer <= 0) {
      bubbleTimer = 200 + Math.random() * 500;
      const s = bubbles.findIndex(b => !b.active);
      if (s >= 0) bubbles[s].ctrl.activate(TANK_L + 20 + Math.random() * (TANK_R - TANK_L - 40));
    }

    // Debug profiler (update every 500ms)
    debugTimer -= delta;
    if (debugTimer <= 0) {
      debugTimer = 500;
      const p = debug.getFrameProfile();
      setDebugInfo(`props/f: ${p.setPropertyCalls}  ${p.frameTimeMs.toFixed(1)}ms`);
    }
  };

  const sel = () => selIdx() >= 0 ? fish[selIdx()] : null;

  return (
    <Game width={W} height={H} backgroundColor={0x0a1a2e} parent="game-container"
      onPointerDown={handlePointerDown}>
      <GameLoop onUpdate={handleUpdate} />

      {/* Title Screen */}
      <Show when={phase() === "title"}>
        <rectangle x={W / 2} y={H / 2} width={W} height={H}
          fillColor={0x0a1a2e} origin={0.5} depth={100} />
        <text x={W / 2} y={H / 2 - 40} text="Solidion Aquarium"
          fontSize={36} fontFamily="Georgia, serif" color="#4488cc" origin={0.5} depth={101} />
        <text x={W / 2} y={H / 2 + 20} text="tap to start"
          fontSize={16} fontFamily="monospace" color="#336688" origin={0.5} depth={101} />
        <ellipse x={W / 2} y={H / 2 + 80} width={32} height={18}
          fillColor={0x4ecdc4} origin={0.5} depth={101} alpha={0.6} />
        <rectangle x={W / 2 - 18} y={H / 2 + 80} width={10} height={12}
          fillColor={0x4ecdc4} origin={0.5} depth={101} alpha={0.5} />
      </Show>

      {/* Aquarium scene with Preload */}
      <Show when={phase() === "aquarium"}>
        <Scene name="aquarium">
          <Preload
        assets={ASSETS}
        fallback={
          <>
            <rectangle x={W / 2} y={H / 2} width={W} height={H}
              fillColor={0x0a1a2e} origin={0.5} depth={50} />
            <text x={W / 2} y={H / 2 - 10} text="Loading aquarium..."
              fontSize={16} fontFamily="monospace" color="#336688" origin={0.5} depth={51} />
            <ellipse x={W / 2} y={H / 2 + 30} width={20} height={12}
              fillColor={0x4ecdc4} origin={0.5} depth={51} alpha={0.5} />
          </>
        }
      >

      {/* Tank */}
      <rectangle x={W / 2} y={SURFACE_Y + (FLOOR_Y - SURFACE_Y) / 2}
        width={W - 40} height={FLOOR_Y - SURFACE_Y}
        fillColor={0x0e2040} origin={0.5} depth={0} alpha={0.5} />
      <rectangle x={W / 2} y={FLOOR_Y + 15} width={W - 40} height={30}
        fillColor={0x8b7355} origin={0.5} depth={1} />
      <rectangle x={W / 2} y={SURFACE_Y} width={W - 40} height={2}
        fillColor={0x4488aa} origin={0.5} depth={5} alpha={0.5} />

      {/* Seaweed (5) */}
      {[{ x: 80, h: 40 }, { x: 200, h: 55 }, { x: 350, h: 70 }, { x: 500, h: 85 }, { x: 580, h: 60 }]
        .map((sw, i) => <Seaweed x={sw.x} height={sw.h} index={i} />)}

      {/* Jellyfish (2) */}
      <Jellyfish baseX={520} baseY={150} />
      <Jellyfish baseX={120} baseY={200} />

      {/* Bubbles pool */}
      {Array.from({ length: MAX_BUBBLES }, (_, i) => <Bubble slot={i} />)}

      {/* Food pool */}
      {Array.from({ length: MAX_FOOD }, (_, i) => <Food slot={i} />)}

      {/* Fish pool */}
      {Array.from({ length: MAX_FISH }, (_, i) => <Fish slot={i} onSelect={selectFish} />)}

      {/* Fry pool (baby fish following parents) */}
      {Array.from({ length: MAX_FRY }, (_, j) => <Fry slot={j} />)}

      {/* HUD */}
      <Show when={phase() === "aquarium"}>
        <rectangle x={W - 60} y={16} width={100} height={24}
          fillColor={0x225588} origin={0.5} depth={20} onClick={() => spawnFish()} />
        <text x={W - 60} y={16} text="+ Add Fish"
          fontSize={11} fontFamily="monospace" color="#aaccee" origin={0.5} depth={21} />
        <text x={20} y={16} text={`Fish: ${fishCount()}`}
          fontSize={12} fontFamily="monospace" color="#668899" originX={0} originY={0.5} depth={20} />
        <text x={20} y={H - 10} text={debugInfo()}
          fontSize={9} fontFamily="monospace" color="#334455" originX={0} originY={0.5} depth={20} />
      </Show>

      {/* Stats Panel — slides in/out via useSpring + SpringBehavior on title */}
      {(() => {
        const panelTarget = () => ({ x: showPanel() && selIdx() >= 0 ? W - 80 : W + 100, y: H / 2 });
        const panelPos = useSpring({ target: panelTarget, stiffness: 80, damping: 14, initial: { x: W + 100, y: H / 2 } });
        const px = () => panelPos().x;
        const pv = () => px() < W; // visible when on-screen
        let titleRef: any = null;
        return (
          <>
            <rectangle x={px()} y={H / 2} width={140} height={180}
              fillColor={0x112233} origin={0.5} depth={30} alpha={0.9} visible={pv()} />
            <text x={px()} y={H / 2 - 60} text={`Fish #${sel()?.id ?? ""}`}
              fontSize={14} fontFamily="monospace" color="#88bbdd" origin={0.5} depth={31}
              visible={pv()} ref={(el: any) => { titleRef = el; }} />
            {/* L1c: SpringBehavior adds subtle bouncy sway to the title text */}
            {titleRef && <SpringBehavior parent={titleRef}
              target={() => ({ x: 0, y: 0 })} stiffness={30} damping={3} />}
            <text x={px()} y={H / 2 - 30} text={`State: ${sel()?.state ?? ""}`}
              fontSize={11} fontFamily="monospace" color="#668899" origin={0.5} depth={31} visible={pv()} />
            <text x={px()} y={H / 2 - 10} text={`Hunger: ${Math.floor(sel()?.hunger ?? 0)}`}
              fontSize={11} fontFamily="monospace" color="#668899" origin={0.5} depth={31} visible={pv()} />
            <rectangle x={px()} y={H / 2 + 30} width={80} height={24}
              fillColor={0x884444} origin={0.5} depth={31} onClick={releaseFish} visible={pv()} />
            <text x={px()} y={H / 2 + 30} text="Release"
              fontSize={11} fontFamily="monospace" color="#ffaaaa" origin={0.5} depth={32} visible={pv()} />
            <rectangle x={px()} y={H / 2 + 60} width={80} height={24}
              fillColor={0x444466} origin={0.5} depth={31}
              onClick={() => { setSelIdx(-1); setShowPanel(false); }} visible={pv()} />
            <text x={px()} y={H / 2 + 60} text="Close"
              fontSize={11} fontFamily="monospace" color="#aaaacc" origin={0.5} depth={32} visible={pv()} />
          </>
        );
      })()}

          </Preload>
        </Scene>
      </Show>
    </Game>
  );
}

// ── Mount ──
createRoot(() => {
  const el = App();
  if (el instanceof HTMLElement) document.getElementById("game-container")?.appendChild(el);
});
