/**
 * AUTO-GENERATED — Do not edit manually.
 * Generated by: scripts/generate-types.ts
 * Source: node_modules/phaser/types/phaser.d.ts
 * Generated: 2026-03-22
 */

import type Phaser from "phaser";
import type { JSX as SolidJSX } from "solid-js";

// ---- Common property groups ----

export interface TransformProps {
  x?: number;
  y?: number;
  angle?: number;
  rotation?: number;
  scale?: number;
  scaleX?: number;
  scaleY?: number;
}

export interface DisplayProps {
  alpha?: number;
  visible?: boolean;
  tint?: number;
  blendMode?: number | string;
  depth?: number;
}

export interface OriginProps {
  origin?: number;
  originX?: number;
  originY?: number;
}

export interface SizeProps {
  width?: number;
  height?: number;
  displayWidth?: number;
  displayHeight?: number;
}

export interface EventProps {
  // L0 aliases
  onClick?: (pointer: Phaser.Input.Pointer, localX: number, localY: number, event: Phaser.Types.Input.EventData) => void;
  // L1 precise events
  onPointerDown?: (pointer: Phaser.Input.Pointer, localX: number, localY: number, event: Phaser.Types.Input.EventData) => void;
  onPointerUp?: (pointer: Phaser.Input.Pointer, localX: number, localY: number, event: Phaser.Types.Input.EventData) => void;
  onPointerOver?: (pointer: Phaser.Input.Pointer, localX: number, localY: number, event: Phaser.Types.Input.EventData) => void;
  onPointerOut?: (pointer: Phaser.Input.Pointer) => void;
  onPointerMove?: (pointer: Phaser.Input.Pointer, localX: number, localY: number, event: Phaser.Types.Input.EventData) => void;
  // Drag
  onDragStart?: (pointer: Phaser.Input.Pointer, dragX: number, dragY: number) => void;
  onDrag?: (pointer: Phaser.Input.Pointer, dragX: number, dragY: number) => void;
  onDragEnd?: (pointer: Phaser.Input.Pointer, dragX: number, dragY: number) => void;
  // Lifecycle
  onAnimationComplete?: (animation: Phaser.Animations.Animation, frame: Phaser.Animations.AnimationFrame) => void;
  onDestroy?: () => void;
}

export interface InteractiveProps {
  interactive?: boolean | Phaser.Types.Input.InputConfiguration;
}

export interface RefProps<T> {
  ref?: ((el: T) => void) | { current: T | null };
}

/** Shape-common fill/stroke props, shared by all Shape subclasses. */
export interface ShapeStyleProps {
  fillColor?: number;
  fillAlpha?: number;
  strokeColor?: number;
  strokeAlpha?: number;
  lineWidth?: number;
}

export type BaseProps = TransformProps & DisplayProps & OriginProps & SizeProps & EventProps & InteractiveProps;

// ---- Per-GameObject props (auto-generated from Phaser types) ----

export interface DynamicBitmapTextProps extends BaseProps {
  font: string;
  scrollX?: number;
  scrollY?: number;
  cropWidth?: number;
  cropHeight?: number;
  displayCallback?: Phaser.Types.GameObjects.BitmapText.DisplayCallback;
  callbackData?: Phaser.Types.GameObjects.BitmapText.DisplayCallbackConfig;
  ref?: ((el: Phaser.GameObjects.DynamicBitmapText) => void) | { current: Phaser.GameObjects.DynamicBitmapText | null };
  children?: SolidJSX.Element;
}

export interface BitmapTextProps extends BaseProps {
  font: string;
  wordWrapCharCode?: number;
  dropShadowX?: number;
  dropShadowY?: number;
  dropShadowColor?: number;
  dropShadowAlpha?: number;
  fontSize?: number;
  letterSpacing?: number;
  lineSpacing?: number;
  text?: string | string[];
  dropShadow?: number;
  characterTint?: number;
  wordTint?: string | number;
  maxWidth?: number;
  align?: number;
  ref?: ((el: Phaser.GameObjects.BitmapText) => void) | { current: Phaser.GameObjects.BitmapText | null };
  children?: SolidJSX.Element;
}

export interface ContainerProps extends TransformProps, DisplayProps, EventProps, InteractiveProps {
  ref?: ((el: Phaser.GameObjects.Container) => void) | { current: Phaser.GameObjects.Container | null };
  children?: SolidJSX.Element;
}

export interface GraphicsProps extends TransformProps, DisplayProps, EventProps, InteractiveProps {
  defaultStyles?: Phaser.Types.GameObjects.Graphics.Styles;
  ref?: ((el: Phaser.GameObjects.Graphics) => void) | { current: Phaser.GameObjects.Graphics | null };
  children?: SolidJSX.Element;
}

export interface ImageProps extends BaseProps {
  texture: string;
  frame?: string | number;
  ref?: ((el: Phaser.GameObjects.Image) => void) | { current: Phaser.GameObjects.Image | null };
  children?: SolidJSX.Element;
}

export interface NineSliceProps extends BaseProps {
  texture: string;
  frame?: string | number;
  leftWidth?: number;
  rightWidth?: number;
  topHeight?: number;
  bottomHeight?: number;
  ref?: ((el: Phaser.GameObjects.NineSlice) => void) | { current: Phaser.GameObjects.NineSlice | null };
  children?: SolidJSX.Element;
}

export interface PointLightProps extends BaseProps {
  color?: Phaser.Display.Color;
  intensity?: number;
  attenuation?: number;
  radius?: number;
  ref?: ((el: Phaser.GameObjects.PointLight) => void) | { current: Phaser.GameObjects.PointLight | null };
  children?: SolidJSX.Element;
}

export interface ArcProps extends BaseProps, ShapeStyleProps {
  iterations?: number;
  radius?: number;
  startAngle?: number;
  endAngle?: number;
  anticlockwise?: boolean;
  ref?: ((el: Phaser.GameObjects.Arc) => void) | { current: Phaser.GameObjects.Arc | null };
  children?: SolidJSX.Element;
}

export interface CurveProps extends BaseProps, ShapeStyleProps {
  smoothness?: number;
  ref?: ((el: Phaser.GameObjects.Curve) => void) | { current: Phaser.GameObjects.Curve | null };
  children?: SolidJSX.Element;
}

export interface EllipseProps extends BaseProps, ShapeStyleProps {
  smoothness?: number;
  ref?: ((el: Phaser.GameObjects.Ellipse) => void) | { current: Phaser.GameObjects.Ellipse | null };
  children?: SolidJSX.Element;
}

export interface GridProps extends BaseProps, ShapeStyleProps {
  cellWidth?: number;
  cellHeight?: number;
  showCells?: boolean;
  outlineFillColor?: number;
  outlineFillAlpha?: number;
  showOutline?: boolean;
  showAltCells?: boolean;
  altFillColor?: number;
  altFillAlpha?: number;
  altFillStyle?: number;
  outlineStyle?: number;
  ref?: ((el: Phaser.GameObjects.Grid) => void) | { current: Phaser.GameObjects.Grid | null };
  children?: SolidJSX.Element;
}

export interface IsoBoxProps extends BaseProps, ShapeStyleProps {
  projection?: number;
  fillTop?: number;
  fillLeft?: number;
  fillRight?: number;
  showTop?: boolean;
  showLeft?: boolean;
  showRight?: boolean;
  faces?: boolean;
  ref?: ((el: Phaser.GameObjects.IsoBox) => void) | { current: Phaser.GameObjects.IsoBox | null };
  children?: SolidJSX.Element;
}

export interface IsoTriangleProps extends BaseProps, ShapeStyleProps {
  projection?: number;
  fillTop?: number;
  fillLeft?: number;
  fillRight?: number;
  showTop?: boolean;
  showLeft?: boolean;
  showRight?: boolean;
  isReversed?: boolean;
  reversed?: boolean;
  faces?: boolean;
  ref?: ((el: Phaser.GameObjects.IsoTriangle) => void) | { current: Phaser.GameObjects.IsoTriangle | null };
  children?: SolidJSX.Element;
}

export interface LineProps extends BaseProps, ShapeStyleProps {
  ref?: ((el: Phaser.GameObjects.Line) => void) | { current: Phaser.GameObjects.Line | null };
  children?: SolidJSX.Element;
}

export interface PolygonProps extends BaseProps, ShapeStyleProps {
  ref?: ((el: Phaser.GameObjects.Polygon) => void) | { current: Phaser.GameObjects.Polygon | null };
  children?: SolidJSX.Element;
}

export interface RectangleProps extends BaseProps, ShapeStyleProps {
  rounded?: number;
  ref?: ((el: Phaser.GameObjects.Rectangle) => void) | { current: Phaser.GameObjects.Rectangle | null };
  children?: SolidJSX.Element;
}

export interface StarProps extends BaseProps, ShapeStyleProps {
  points?: number;
  innerRadius?: number;
  outerRadius?: number;
  ref?: ((el: Phaser.GameObjects.Star) => void) | { current: Phaser.GameObjects.Star | null };
  children?: SolidJSX.Element;
}

export interface TriangleProps extends BaseProps, ShapeStyleProps {
  ref?: ((el: Phaser.GameObjects.Triangle) => void) | { current: Phaser.GameObjects.Triangle | null };
  children?: SolidJSX.Element;
}

export interface SpriteProps extends BaseProps {
  texture: string;
  frame?: string | number;
  animation?: string | Phaser.Types.Animations.PlayAnimationConfig;
  ref?: ((el: Phaser.GameObjects.Sprite) => void) | { current: Phaser.GameObjects.Sprite | null };
  children?: SolidJSX.Element;
}

export interface TextProps extends BaseProps {
  style?: Phaser.Types.GameObjects.Text.TextStyle;
  wordWrap?: { width: number; useAdvancedWrap?: boolean };
  autoRound?: boolean;
  padding?: Phaser.Types.GameObjects.Text.TextPadding;
  lineSpacing?: number;
  letterSpacing?: number;
  text?: string | string[];
  font?: string;
  fontFamily?: string;
  fontSize?: string | number;
  fontStyle?: string;
  fixedSize?: number;
  backgroundColor?: string;
  fill?: string | CanvasGradient | CanvasPattern;
  color?: string | CanvasGradient | CanvasPattern;
  stroke?: string | CanvasGradient | CanvasPattern;
  shadow?: number;
  shadowOffset?: number;
  shadowColor?: string;
  shadowBlur?: number;
  shadowStroke?: boolean;
  shadowFill?: boolean;
  wordWrapWidth?: number | null;
  wordWrapCallback?: any;
  align?: string;
  resolution?: number;
  maxLines?: number;
  rTL?: boolean;
  ref?: ((el: Phaser.GameObjects.Text) => void) | { current: Phaser.GameObjects.Text | null };
  children?: SolidJSX.Element;
}

export interface TileSpriteProps extends BaseProps {
  texture: string;
  frame?: string | number;
  tilePosition?: number;
  tileScale?: number;
  tilePositionX?: number;
  tilePositionY?: number;
  tileScaleX?: number;
  tileScaleY?: number;
  ref?: ((el: Phaser.GameObjects.TileSprite) => void) | { current: Phaser.GameObjects.TileSprite | null };
  children?: SolidJSX.Element;
}

export interface ZoneProps extends TransformProps, SizeProps, EventProps, InteractiveProps {
  circleDropZone?: number;
  rectangleDropZone?: number;
  dropZone?: object;
  ref?: ((el: Phaser.GameObjects.Zone) => void) | { current: Phaser.GameObjects.Zone | null };
  children?: SolidJSX.Element;
}

// ---- JSX namespace declaration ----

declare module "solid-js" {
  namespace JSX {
    interface IntrinsicElements {
      dynamicBitmapText: DynamicBitmapTextProps;
      bitmapText: BitmapTextProps;
      container: ContainerProps;
      graphics: GraphicsProps;
      image: ImageProps;
      nineslice: NineSliceProps;
      pointLight: PointLightProps;
      arc: ArcProps;
      curve: CurveProps;
      ellipse: EllipseProps;
      grid: GridProps;
      isoBox: IsoBoxProps;
      isoTriangle: IsoTriangleProps;
      line: LineProps;
      polygon: PolygonProps;
      rectangle: RectangleProps;
      star: StarProps;
      triangle: TriangleProps;
      sprite: SpriteProps;
      text: TextProps;
      tileSprite: TileSpriteProps;
      zone: ZoneProps;
    }
  }
}
